React eslint
Brane-Hubsch/dotfiles pull request #1
Opened 2023-04-07 07:42 UTC by antonnystedt

2023-04-07 15:03 UTC, albinhubsch requested changes

2023-04-07 15:03 UTC, albinhubsch commented on react/.eslintrc.json
> +  "rules": {
can we add `"prettier/prettier": "error"` to the rules section :)?

2023-04-07 15:03 UTC, albinhubsch commented on react/.eslintrc.json
> +  "plugins": ["react-hooks", "@typescript-eslint"],
add prettier to the plugins array

2023-04-08 05:24 UTC, antonnystedt commented on react/.eslintrc.json
> +  "plugins": ["react-hooks", "@typescript-eslint"],
Don't know if it makes a difference since we have "plugin:prettier/recommended" in the extends array, but adding it anyway

2023-04-08 07:31 UTC, albinhubsch commented on react/.eslintrc.json
> +  "plugins": ["react-hooks", "@typescript-eslint"],
ah, true. merging in, we can always change later as well :)

2023-04-08 07:31 UTC, merged